# Generated by Django 4.1.7 on 2023-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('emp_holiday', models.IntegerField()),
                ('emp_holiday_approved', models.IntegerField()),
                ('emp_holiday_pending', models.IntegerField()),
                ('emp_holiday_reject', models.IntegerField()),
            ],
        ),
    ]
